PImage menuI;
PImage ingameHudI;
PImage TabMenuI;
PImage hitScreenI;
PImage diamondBuyI;

PImage floorI;
PImage floor1I;
PImage floor2I;
PImage floor3I;
PImage stoneI;
PImage treeI;
PImage treeRipeI;
PImage saplingI;
PImage stone2I;
PImage tree2I;
PImage weirdTreeI;
PImage weirdPilzI;
PImage weirdGrasI;
PImage grasI;
PImage pilzI;
PImage spikeI;
PImage dungeonI;
PImage caveClearedI;
PImage chestI;
PImage chestOpenI;
PImage scrapperI;
PImage shopI;
PImage tentI;
PImage scrapMillI;
PImage cutWheatI;
PImage wheatI;
PImage redChestI;
PImage openredChestI;
PImage vaseI;
PImage graveI;
PImage graveOpendI;
PImage ripBagI;
PImage tuckaI;
PImage bombfassI;
PImage posionI;
PImage traderI;
PImage crazyTraderI;

PImage commonASRingI;
PImage commonEnergyI;
PImage commonMagUpI;
PImage commonOilI;
PImage commonSharkbiteI;
PImage commonScopeI;
PImage commonCammoShortsI;
PImage commonFoodI;
PImage steakI;
PImage commonSlowI;
PImage commonSilencerI;
PImage commonElefantI;
PImage commonTalonI;
PImage commonTridentI;
PImage commonHeartI;
PImage commonPlugI;
PImage commonManaI;
PImage rareTrippleDaggerI;
PImage rareDaggerI;
PImage rareBloodI;
PImage rareCampI;
PImage campMapI;
PImage rareDartsI;
PImage rarePepperI;
PImage rareRhinoI;
PImage rareSneakerI;
PImage rareDiamondI;
PImage rareMixerI;
PImage rareMagnetI;
PImage rareCrawI;
PImage rareMeatI;
PImage rareSlowI;
PImage rareExtendoI;
PImage rareStealthI;
PImage rareSpeedI;
PImage rareOilI;
PImage rareSilincerI;
PImage rareChestI;
PImage rareNinjaI;
PImage rareWarriorI;
PImage rareRevolverI;
PImage rareTridentI;
PImage rareMagicHatI;
PImage rareBlueCheesI;
PImage rarePunchI;
PImage ravenItemI;
PImage sandclockI;
PImage sniperItemI;
PImage allStatsUpI;
PImage elephantI;
PImage stickyBombI;
PImage superRareMagInAHatI;
PImage superRareGoldDaggerI;
PImage superRareKalashnikovI;
PImage superRarePoisonI;
PImage superRareBiohazardI;
PImage superRareDartsI;
PImage superRareShotgunI;
PImage superRareSneakerI;
PImage superRareSniperI;
PImage superRareTentI;
PImage superRareBloodI;
PImage superRareTridentI;
PImage goldSpinnyGunI;
PImage goldShotgunI;
PImage goldSniperI;
PImage goldAKI;
PImage customDNAI;
PImage customDNA2I;
PImage customNuggetI;
PImage flute1I;
PImage flute2I;
PImage flute3I;
PImage drillI;

PImage classMadManI;
PImage redAttackspeedRageI;
PImage redMassacreI;
PImage redbulletRainI;
PImage magicDieI;
PImage ninjaDashI;
PImage axeThrowI;
PImage axeMapI;
PImage whiteMonsterI;

PImage playerI;
PImage sniperI;
PImage markI;

PImage assasinI; 
PImage blueI;
PImage redOctoI;
PImage rocketI; 
PImage rightHandI; 
PImage guardianI;
PImage teleportEnemyI;
PImage FishHeadI; 
PImage FishBodyI; 
PImage FishTailI; 
PImage KingI;
PImage FlyI;
PImage SpikerI;
PImage BulldozerI;
PImage arrowI;
PImage RatI;
PImage HiveI;
PImage BeeI;
PImage redSpeederI;
PImage ravenBossI;
PImage ravenBulletI;
PImage ravenTentI;
PImage wandererI;
PImage SpawnerBossI;
PImage HoneyPotI;
PImage rangeIndI;
PImage chainRedI;

PImage blueBulletI;
PImage redBulletI;
PImage grayBulletI;
PImage crossBulletI;
PImage streamBulletI;
PImage schrottBulletI;
PImage explosionI;
PImage rocketTechI;
PImage cheeseBulletI;
PImage greenBulletI;
PImage spikeBulletI;
PImage DaggerBulletI;

PImage emperorI;
PImage techpriestI;
PImage vampireI;
PImage hivemasterI;
PImage shrekI;
PImage actualyI;
PImage pocornI;
PImage hellokittyI;
PImage discoI;
PImage skullI;
PImage fishI;
PImage raphiI;
PImage deathI;
PImage baneI;
PImage morpheusI;
PImage clownI;
PImage charlyBrownI;
PImage glitchI;
PImage bombSkinI;

PImage coin1I;
PImage scrap1I;
PImage appleI;
PImage grayCrytalI;
PImage greenCrytalI;

void loadImg(){
  menuI=loadImage("menu.PNG");
  ingameHudI=loadImage("ingameHud.PNG");
  TabMenuI=loadImage("TabMenu.PNG");
  hitScreenI=loadImage("hitScreen.PNG");
  diamondBuyI=loadImage("diamondBuy.PNG");
  
  emperorI=loadImage("emperor.png");
  techpriestI=loadImage("techpriest.png");
  vampireI=loadImage("vampire.png");
  hivemasterI=loadImage("hivemaster.png");
  shrekI=loadImage("shrek.png");
  actualyI=loadImage("actualy.png");
  pocornI=loadImage("pocorn.png");
  hellokittyI=loadImage("hellokitty.png");
  discoI=loadImage("disco.png");
  skullI=loadImage("skull.png");
  fishI=loadImage("fish.png");
  raphiI=loadImage("raphi.png");
  deathI=loadImage("death.png");
  baneI=loadImage("bane.png");
  morpheusI=loadImage("morpheus.png");
  clownI=loadImage("clown.png");
  charlyBrownI=loadImage("charlyBrown.png");
  glitchI=loadImage("glitch.png");  
  bombSkinI=loadImage("bombSkin.png");  
  
  arrowI=loadImage("arrow.png");
  floorI = loadImage("Floor.png");
  floor1I = loadImage("Floor1.png");
  floor2I = loadImage("Floor2.png");
  floor3I = loadImage("Floor3.png");
  stoneI = loadImage("stone.png");
  treeI = loadImage("tree.png");
  treeRipeI = loadImage("treeRipe.png");
  saplingI = loadImage("sapling.png");
  stone2I = loadImage("stone2.png");
  tree2I = loadImage("tree2.png");
  weirdTreeI = loadImage("weirdTree.png");
  weirdPilzI = loadImage("bigPilz.png");
  weirdGrasI = loadImage("weirdGras.png");
  grasI = loadImage("gras.png");
  pilzI = loadImage("pilz.png");
  spikeI = loadImage("spike.png");
  dungeonI = loadImage("dungeon.png");
  caveClearedI = loadImage("caveCleared.png");
  chestI = loadImage("chest.png");
  chestOpenI = loadImage("chestOpen.png");
  scrapperI = loadImage("scrapper.png");
  shopI = loadImage("shop.png");
  tentI = loadImage("tent.png");
  scrapMillI = loadImage("scrapMill.png");
  cutWheatI = loadImage("cutWheat.png");
  wheatI = loadImage("wheat.png");
  redChestI = loadImage("redChest.png");
  openredChestI = loadImage("openredChest.png");
  vaseI = loadImage("vase.png");
  graveI = loadImage("grave.png");
  graveOpendI = loadImage("graveOpened.png");
  ripBagI= loadImage("RipBag.png");
  tuckaI= loadImage("tucka.png");
  bombfassI= loadImage("bombfass.png");
  posionI= loadImage("posion.png");
  traderI= loadImage("trader.png");
  crazyTraderI= loadImage("crazyTrader.png");
  
  commonASRingI = loadImage("commonASRing.png");
  commonEnergyI = loadImage("commonEnergy.png");
  commonMagUpI = loadImage("commonMagUp.png");
  commonOilI = loadImage("commonOil.png");
  commonSharkbiteI = loadImage("commonSharkbite.png");
  commonScopeI = loadImage("commonScope.png");
  commonCammoShortsI = loadImage("commonCammoShorts.png");
  commonFoodI = loadImage("commonFood.png");
  steakI = loadImage("steak.png");
  commonSlowI = loadImage("slow.png");
  commonSilencerI = loadImage("silencer.png");
  commonElefantI = loadImage("elefant.png");
  commonTalonI = loadImage("talon.png");
  commonTridentI = loadImage("trident2.png");
  commonHeartI = loadImage("commonHeart.png");
  commonPlugI = loadImage("commonPlug.png");
  commonManaI = loadImage("commonManaUp.png");
  rareTrippleDaggerI = loadImage("trippleDagger.png");
  rareDaggerI = loadImage("dagger.png");
  rareBloodI = loadImage("blood.png");
  rareCampI = loadImage("camp.png");
  campMapI = loadImage("campMap.png");
  rareDartsI = loadImage("darts.png");
  rarePepperI = loadImage("pepper.png");
  rareRhinoI = loadImage("rhino.png");
  rareSneakerI = loadImage("sneaker.png");
  rareDiamondI = loadImage("diamond.png");
  rareMixerI = loadImage("mixer.png");
  rareMagnetI = loadImage("magnet.png");
  rareCrawI = loadImage("craw.png");
  rareMeatI = loadImage("meat2.png");
  rareSlowI = loadImage("slow2.png");
  rareExtendoI = loadImage("extendo.png");
  rareStealthI = loadImage("stealth2.png");
  rareSpeedI = loadImage("speed2.png");
  rareOilI = loadImage("reload2.png");
  rareSilincerI = loadImage("silencer2.png");
  rareChestI = loadImage("tresureChest.png");
  rareNinjaI = loadImage("ninja.png");
  rareRevolverI = loadImage("revolver.png");
  rareTridentI = loadImage("trident.png");
  rareMagicHatI = loadImage("magicHat.png");
  rareBlueCheesI = loadImage("blueChees.png");
  rarePunchI = loadImage("punch.png");
  rareWarriorI = loadImage("warrior.png");
  ravenItemI = loadImage("ravenItem.png");
  drillI = loadImage("drill.png");
  stickyBombI = loadImage("stickyBomb.png");
  sandclockI = loadImage("sandclock.png");
  sniperItemI = loadImage("hyperScope.png");
  allStatsUpI = loadImage("allStatsUp.png");
  elephantI = loadImage("Elephant.png");
  superRareMagInAHatI = loadImage("magInAHat.png");
  superRareGoldDaggerI= loadImage("goldDagger.png");
  superRareKalashnikovI = loadImage("Kalashnikov.png");
  superRarePoisonI = loadImage("poison.png");
  superRareBiohazardI = loadImage("biohazard.png");
  superRareDartsI = loadImage("redDarts.png");
  superRareShotgunI = loadImage("redShotgun.png");
  superRareSneakerI = loadImage("redSneaker.png");
  superRareSniperI = loadImage("redSniper.png");
  superRareTentI = loadImage("redTent.png");
  superRareBloodI = loadImage("redBlood.png");
  superRareTridentI = loadImage("trident3.png");
  goldSpinnyGunI = loadImage("spinnyGun.png");
  goldShotgunI = loadImage("goldShotgun.png");
  goldSniperI = loadImage("goldSniper.png");
  goldAKI = loadImage("goldAK.png");
  customDNAI = loadImage("dna.png");
  customDNA2I = loadImage("DNA2.png");
  customNuggetI = loadImage("nugget.png");
  
  classMadManI = loadImage("madMan.png");
  redAttackspeedRageI = loadImage("redAttackspeedRage.png");
  redMassacreI = loadImage("redMassacre.png");
  redbulletRainI = loadImage("redbulletRain.png");
  magicDieI=loadImage("magicDie.png");
  ninjaDashI=loadImage("ninjaDash.png");
  axeThrowI=loadImage("axeThrow.png");
  axeMapI=loadImage("axeMap.png");
  whiteMonsterI=loadImage("whiteMonster.png");
  
  flute1I= loadImage("fishFlute.png");
  flute2I= loadImage("swarmFlute.png");
  flute3I= loadImage("spikeFlute.png");
  
  playerI = loadImage("player.png");
  sniperI = loadImage("Sniper.png");
  markI = loadImage("mark.png");
  
  assasinI = loadImage("Assasin.png");
  blueI = loadImage("blue.png");
  rocketI = loadImage("rocket.png");
  rightHandI = loadImage("RightHand.png");
  guardianI = loadImage("Guardian2.png");
  FishHeadI = loadImage("FishHead.png"); 
  FishBodyI = loadImage("FishBody.png");  
  FishTailI = loadImage("FishTail.png");
  KingI = loadImage("King.png");
  FlyI = loadImage("Fly.png");
  teleportEnemyI = loadImage("teleportEnemy.png");
  BulldozerI = loadImage("bulldozer.png");
  SpikerI = loadImage("spiker.png");
  RatI = loadImage("Rat.png");
  HiveI = loadImage("hiveRaid.png");
  BeeI = loadImage("bee.png");
  redOctoI = loadImage("redOcto.png");
  redSpeederI = loadImage("zombie.png");
  ravenBossI = loadImage("raven.png");
  ravenBulletI= loadImage("ravenBullet.png");
  ravenTentI= loadImage("ravenTent.png");
  wandererI= loadImage("wanderer.png");
  SpawnerBossI= loadImage("SpawnerBoss.png");
  HoneyPotI= loadImage("HoneyPot.png");
  rangeIndI= loadImage("rangeInd.png");
  chainRedI= loadImage("chainRed.png");
  
  blueBulletI = loadImage("blueBullet.png");
  redBulletI = loadImage("redBullet.png");
  grayBulletI = loadImage("grayBullet.png");
  crossBulletI = loadImage("krossBullet.png");
  streamBulletI = loadImage("streamBullet.png");
  schrottBulletI = loadImage("schrottBullet.png");
  explosionI = loadImage("explosion.png");
  rocketTechI = loadImage("rocketTech.png");
  cheeseBulletI = loadImage("cheeseBullet.png");
  greenBulletI = loadImage("greenBullet.png");
  spikeBulletI = loadImage("spikeBullet.png");
  DaggerBulletI = loadImage("DaggerBullet.png");
  
  coin1I = loadImage("coin1.png");
  scrap1I = loadImage("scrap1.png");
  appleI = loadImage("Apple.png");
  grayCrytalI = loadImage("grayCrytal.png");
  greenCrytalI = loadImage("greenCrytal.png");
}

void loadGameState(){
  table= loadTable("player.csv","header,csv");
  money=table.getInt(1,"value");
  diamonds=table.getInt(2,"value");
  timeChrystal=table.getInt(3,"value");
  greenChrystal=table.getInt(4,"value");
  skinPicked=table.getInt(5,"value");
  highscore=table.getInt(6,"value");
  
  for(int i=0;i<skins.size();i++){
    if(table.getInt(10+i,"value") ==1) skins.get(i).unlocked=true;
    else skins.get(i).unlocked=false;
    
    if(table.getInt(10+i,"posY") ==1) skins.get(i).m.finished=true;
    else skins.get(i).m.finished=false;
    
    skins.get(i).m.score=table.getFloat(10+i,"posX");
  }
}

void save(){
  table= loadTable("player.csv","header,csv");
  table.getRow(1).setFloat("value",money);
  table.getRow(2).setFloat("value",diamonds);
  table.getRow(3).setFloat("value",timeChrystal);
  table.getRow(4).setFloat("value",greenChrystal);
  table.getRow(5).setFloat("value",skinPicked);
  table.getRow(6).setFloat("value",highscore);
  
  for(int i=0;i<skins.size();i++){
    if(skins.get(i).unlocked) table.getRow(10+i).setInt("value",1);
    else table.getRow(10+i).setInt("value",0);
    
    if(skins.get(i).m.finished) table.getRow(10+i).setInt("posY",1);
    else table.getRow(10+i).setInt("posY",0);
    
    table.getRow(10+i).setFloat("posX",skins.get(i).m.score);
  }
  saveTable(table, "data/player.csv");
}
